name: versions

on:
  # Trigger manually
  workflow_dispatch:

  # Trigger on any push to the main
  push:
    branches:
      - main
      - development

  # Trigger on any push to a PR that targets main
  pull_request:
    branches:
      - main
      - development

permissions:
  contents: write

env:
  name: "automl_sphinx_theme"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
      fail-fast:  false

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install ".[dev]"

    - name: Make docs
      run: |
        make clean
        make docs